### ISSUE TITLE
【后端】题库

### ISSUE THREAD

**Issue by Momoyeyu** [Momoyeyu/CTF-Website#9]
- [x] Task api实现
- [x] AnswerRecord api 实现

**Comment by WeifeiJin** [comment]
实现：[list_task]，返回特定类型的题目基本信息列表，并且每道题携带当前用户是否已完成该题的信息；[query_one]单题查询，返回题目详细信息（主要是题目描述）。

**Comment by WeifeiJin** [comment]
实现：[list_task]，返回特定类型的题目基本信息列表，并且每道题携带当前用户是否已完成该题的信息；[query_one]单题查询，返回题目详细信息（主要是题目描述）。

**Comment by WeifeiJin** [comment]
实现：Answer.py，两个函数，[download_attachment]，提供附件下载，[commit_flag]，校验flag并给答对的用户加分，增加答题记录，判断首杀并记录。
App-rank，两个函数，user.py中[get_rank]返回用户排名，team.py中[get_rank]返回战队排名。

遗留问题：返回附件时文件关闭问题未解决。

**Comment by Momoyeyu** [comment]
# 进度
## 2023-10-29
- 大部分 api 的 response 已经标准化
- 部分 api 的 exception 逻辑重写
- api 做了一些重组

### 新的 api列表：
#### Tasks
1. list_all()    // 新
2. list_type()   // 改动
3. query_one()   // 改动

#### Answer
1. commit_flag()
2. download_attachment()
3. list_solved()  // 新

**Comment by Momoyeyu** [comment]
API 已经全部实现，等待进一步测试与调试
